spring:
  rabbitmq:
    host: 118.25.87.131
    port: 5672
    username: wangjie
    password: ENC(z7plwK3pw298dm5OYesIF25uGUlSkYOt)
    virtual-host: /
    #发送确认
    publisher-confirms: true
    #无效路由返回
    publisher-returns: true
    template:
      mandatory: true
server:
  port: 21000